name: Build Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image - CPU
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/master'
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_LOCAL_REGISTRY }}/gh-runner:latest
          build-args: |
            - PERSONAL_ACCESS_TOKEN=${{ secrets.GH_TOKEN }}

      - name: Build Docker Image - CPU with Tag
        uses: docker/build-push-action@v2
        if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_LOCAL_REGISTRY }}/gh-runner:${{ github.ref }}
          build-args: |
            - PERSONAL_ACCESS_TOKEN=${{ secrets.GH_TOKEN }}
