name: Test Self-Hosted Runner

on:
  workflow_dispatch:
    inputs:
      runner-name:
        description: "Runner Name"
        required: true
        default: "test"

jobs:
  test-python-lint-and-test:
    runs-on: ${{ github.event.inputs.runner-name }}
    container:
      image: registry.guppy.local/base-python:master
    defaults:
      run:
        working-directory: ./test-python

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: |
          git config --global url."https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          poetry install

      - name: Run flake8 linter
        run: |
          poetry run flake8 .

      - name: Run unittest
        run: |
          poetry run pytest --cov=src -v

  test-build:
    runs-on: test
    env:
      DOCKER_TAG: ${{ secrets.DOCKER_LOCAL_REGISTRY }}/python-test
      VERSION: ${{ github.event.release.tag_name != '' && github.event.release.tag_name || github.ref_name }}
    defaults:
      run:
        working-directory: ./test-python

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ env.DOCKER_TAG }}:${{ env.VERSION }} , ${{ env.DOCKER_TAG }}:latest
          build-args: |
            VERSION=${{ env.VERSION }}
            GIT_SHA=${{ github.sha }}
